const CREATE_ROUTE = "CREATE_ROUTE";
const BUILD_DELIVERY_ROUTE = "BUILD_DELIVERY_ROUTE";
const GET_ROUTES = "GET_ROUTES";
const GET_DELIVERY_ROUTE_COST = "GET_DELIVERY_ROUTE_COST";
const GET_AVAILABLE_ROUTES = "GET_AVAILABLE_ROUTES";

export {
  CREATE_ROUTE,
  BUILD_DELIVERY_ROUTE,
  GET_ROUTES,
  GET_DELIVERY_ROUTE_COST,
  GET_AVAILABLE_ROUTES,
}